### ISSUE TITLE
Compile error in gninalibobj

### ISSUE THREAD

**Issue by ptmodeler** [gnina/gnina#249] opened 2024-03-22 01:41 UTC
### Issue summary
[ 64%] Generating _version.cpp
[ 64%] Building CXX object gninasrc/CMakeFiles/gninalibobj.dir/lib/atom_constants.cpp.o
[ 64%] Building CUDA object gninasrc/CMakeFiles/gninalibobj.dir/lib/bfgs.cu.o
[ 65%] Building CXX object gninasrc/CMakeFiles/gninalibobj.dir/lib/box.cpp.o
[ 65%] Building CXX object gninasrc/CMakeFiles/gninalibobj.dir/lib/builtinscoring.cpp.o
[ 65%] Building CXX object gninasrc/CMakeFiles/gninalibobj.dir/lib/cache.cpp.o
[ 65%] Building CXX object gninasrc/CMakeFiles/gninalibobj.dir/lib/cache_gpu.cpp.o
[ 66%] Building CXX object gninasrc/CMakeFiles/gninalibobj.dir/lib/cnn_scorer.cpp.o
[ 66%] Building CXX object gninasrc/CMakeFiles/gninalibobj.dir/lib/cnn_torch_scorer.cpp.o
[ 66%] Building CXX object gninasrc/CMakeFiles/gninalibobj.dir/lib/cnn_data.cpp.o
[ 66%] Building CXX object gninasrc/CMakeFiles/gninalibobj.dir/lib/coords.cpp.o

In file included from /usr/include/c++/11/tuple:39,
                 from /usr/include/c++/11/functional:54,
                 from /usr/include/c++/11/pstl/glue_algorithm_defs.h:13,
                 from /usr/include/c++/11/algorithm:74,
                 from /mnt/c/Users/Dennis/gnina/gninasrc/lib/common.h:30,
                 from /mnt/c/Users/Dennis/gnina/gninasrc/lib/atom_constants.h:26,
                 from /mnt/c/Users/Dennis/gnina/gninasrc/lib/atom_constants.cpp:1:
/mnt/c/Users/Dennis/gnina/gninasrc/../Eigen/array:8:4: error: #error The Eigen/Array header does no longer exist in Eigen3. All that functionality has moved to Eigen/Core.
    8 |   #error The Eigen/Array header does no longer exist in Eigen3. All that functionality has moved to Eigen/Core.
      |    ^~~~~
In file included from /usr/include/c++/11/pstl/glue_algorithm_defs.h:13,
                 from /usr/include/c++/11/algorithm:74,
                 from /mnt/c/Users/Dennis/gnina/gninasrc/lib/common.h:30,
                 from /mnt/c/Users/Dennis/gnina/gninasrc/lib/atom_constants.h:26,
                 from /mnt/c/Users/Dennis/gnina/gninasrc/lib/atom_constants.cpp:1:
/usr/include/c++/11/functional:1097:13: error: ‘array’ was not declared in this scope; did you mean ‘valarray’?
 1097 |       tuple<array<_Tp, _Len>, _Pred> _M_bad_char;
      |             ^~~~~
      |             valarray
/usr/include/c++/11/functional:1097:28: error: template argument 1 is invalid
 1097 |       tuple<array<_Tp, _Len>, _Pred> _M_bad_char;
      |                            ^
/usr/include/c++/11/functional:1097:28: error: template argument 2 is invalid
/usr/include/c++/11/functional:1097:29: error: expected unqualified-id before ‘,’ token
 1097 |       tuple<array<_Tp, _Len>, _Pred> _M_bad_char;
      |                             ^
/usr/include/c++/11/functional: In constructor ‘std::__boyer_moore_array_base<_Tp, _Len, _Pred>::__boyer_moore_array_base(_RAIter, std::size_t, _Unused&&, _Pred&&)’:
/usr/include/c++/11/functional:1069:11: error: class ‘std::__boyer_moore_array_base<_Tp, _Len, _Pred>’ does not have any field named ‘_M_bad_char’
 1069 |         : _M_bad_char{ array<_Tp, _Len>{}, std::move(__pred) }
      |           ^~~~~~~~~~~
/usr/include/c++/11/functional:1069:24: error: ‘array’ was not declared in this scope; did you mean ‘valarray’?
 1069 |         : _M_bad_char{ array<_Tp, _Len>{}, std::move(__pred) }
      |                        ^~~~~
      |                        valarray
/usr/include/c++/11/functional:1069:33: error: expected primary-expression before ‘,’ token
 1069 |         : _M_bad_char{ array<_Tp, _Len>{}, std::move(__pred) }
      |                                 ^
/usr/include/c++/11/functional:1069:40: error: expected primary-expression before ‘{’ token
 1069 |         : _M_bad_char{ array<_Tp, _Len>{}, std::move(__pred) }
      |                                        ^
/usr/include/c++/11/functional:1069:40: error: expected ‘}’ before ‘{’ token
/usr/include/c++/11/functional:1069:22: note: to match this ‘{’
 1069 |         : _M_bad_char{ array<_Tp, _Len>{}, std::move(__pred) }
      |                      ^
/usr/include/c++/11/functional: In member function ‘std::__boyer_moore_array_base<_Tp, _Len, _Pred>::__diff_type std::__boyer_moore_array_base<_Tp, _Len, _Pred>::_M_lookup(_Key, std::__boyer_moore_array_base<_Tp, _Len, _Pred>::__diff_type) const’:
/usr/include/c++/11/functional:1091:30: error: ‘_M_bad_char’ was not declared in this scope; did you mean ‘__is_char’?
 1091 |           return std::get<0>(_M_bad_char)[__ukey];
      |                              ^~~~~~~~~~~
      |                              __is_char
/usr/include/c++/11/functional: In member function ‘const _Pred& std::__boyer_moore_array_base<_Tp, _Len, _Pred>::_M_pred() const’:
/usr/include/c++/11/functional:1095:44: error: ‘_M_bad_char’ was not declared in this scope; did you mean ‘__is_char’?
 1095 |       _M_pred() const { return std::get<1>(_M_bad_char); }
      |                                            ^~~~~~~~~~~
      |                                            __is_char
make[2]: *** [gninasrc/CMakeFiles/gninalibobj.dir/build.make:206: gninasrc/CMakeFiles/gninalibobj.dir/lib/atom_constants.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1712: gninasrc/CMakeFiles/gninalibobj.dir/all] Error 2
make: *** [Makefile:146: all] Error 2

### Steps to reproduce
Trying to compile gnina as described in the README.

### Your system configuration
Operating system: WSL2 Ubuntu 22.04 
Compiler: gcc 11.4
CUDA version (if applicable): 12.4
CUDNN version (if applicable):  9.0
Python version: 3.10.12

**Comment by dkoes** [comment] 2024-03-22 12:02
Duplicate of #215

**Closed by dkoes** 2024-03-22 12:02 UTC
