### ISSUE TITLE
CPU-only compilation fails

### ISSUE THREAD

**Issue by gwiecz1** [gnina/gnina#159] opened 2022-08-03 14:16 UTC
### Issue summary
It is not possible to compile gnina in CPU-only mode. If the CPU_ONLY flag is used in cmake, all CUDA-related flags remain active. During the compilation, CUDA is persistently being searched, checked and .cu sources compiled regardless of CPU_ONLY and CUDA settings (trying to turn CUDA off). CUDA is installed on the test system, but I do not want it to be used. Finally, the compilation fails at caffe:

<code>
[  5%] Building CXX object caffe/src/caffe/CMakeFiles/caffe.dir/layers/batch_reindex_layer.cpp.o
In file included from /home/gigo/autodock/gnina/github/gnina01/caffe/include/caffe/blob.hpp:8,
                 from /home/gigo/autodock/gnina/github/gnina01/caffe/include/caffe/layers/argmax_layer.hpp:6,
                 from /home/gigo/autodock/gnina/github/gnina01/caffe/src/caffe/layers/argmax_layer.cpp:6:
/home/gigo/autodock/gnina/github/gnina01/caffe/include/caffe/common.hpp: In static member function 'static void caffe::Caffe::device_synchronize()':
/home/gigo/autodock/gnina/github/gnina01/caffe/include/caffe/common.hpp:173:56: error: 'cudaDeviceSynchronize' was not declared in this scope; did you mean 'device_synchronize'?
  173 |   inline static void device_synchronize() { CUDA_CHECK(cudaDeviceSynchronize()); }
      |                                                        ^~~~~~~~~~~~~~~~~~~~~
      |                                                        device_synchronize
In file included from /home/gigo/autodock/gnina/github/gnina01/caffe/include/caffe/blob.hpp:8,
                 from /home/gigo/autodock/gnina/github/gnina01/caffe/include/caffe/layers/accuracy_layer.hpp:6,
                 from /home/gigo/autodock/gnina/github/gnina01/caffe/src/caffe/layers/accuracy_layer.cpp:5:
/home/gigo/autodock/gnina/github/gnina01/caffe/include/caffe/common.hpp: In static member function 'static void caffe::Caffe::device_synchronize()':
/home/gigo/autodock/gnina/github/gnina01/caffe/include/caffe/common.hpp:173:56: error: 'cudaDeviceSynchronize' was not declared in this scope; did you mean 'device_synchronize'?
  173 |   inline static void device_synchronize() { CUDA_CHECK(cudaDeviceSynchronize()); }
      |                                                        ^~~~~~~~~~~~~~~~~~~~~
      |                                                        device_synchronize
/home/gigo/autodock/gnina/github/gnina01/caffe/include/caffe/common.hpp:173:45: error: 'CUDA_CHECK' was not declared in this scope; did you mean 'DCHECK'?
  173 |   inline static void device_synchronize() { CUDA_CHECK(cudaDeviceSynchronize()); }
      |                                             ^~~~~~~~~~
      |                                             DCHECK
</code>

With CUDA and cuDNN, gnina compiles and works fine.
I would be grateful for some hints on how to proceed.
Thank you very much for gnina!
Best,
g

### Steps to reproduce
cd gnina
mkdir build01
cd build01
cmake .. -DCPU_ONLY=ON -DBUILD_python=OFF -DBUILD_python_layer=OFF
make

### Your system configuration
Operating system: Debian sid
Compiler: gcc 12.1.0
CUDA version (if applicable): not applicable
CUDNN version (if applicable): not applicable
Python version: 3.10.5 (not applicable?)
cmake: 3.23.3

**Comment by dkoes** [comment] 2022-09-27 19:30
Currently, you have to build with CUDA, but once it it built you do not have to use it.

**Comment by dkoes** [comment] 2022-10-25 23:52
Duplicate of #168

**Closed by dkoes** 2022-10-25 23:52 UTC
