### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by Glinttsd** [gnina/gnina#142] opened 2022-03-15 03:58 UTC
### Issue summary
nvlink fatal   : Could not open input file '/usr/lib/x86_64-linux-gnu/libpthread.a' (target: sm_86)

### Steps to reproduce
I followed the installation guildline, it worked fine untill `make`
I got these output:
`
[  0%] Performing update step for 'libmolgrid'
[  0%] No patch step for 'libmolgrid'
[  0%] Performing configure step for 'libmolgrid'
-- Current git revision is b9ae032f52fc7a8153987bde09c0efa3620d8bb6
-- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.74.0/BoostConfig.cmake (found version "1.74.0") found components: regex unit_test_framework program_options system filesystem iostreams 
-- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.74.0/BoostConfig.cmake (found version "1.74.0") found components: system filesystem python39 
-- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.74.0/BoostConfig.cmake (found version "1.74.0") found components: unit_test_framework system 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/glinttsd/gnina/build/libmolgrid-prefix/src/libmolgrid-build
[  0%] Performing build step for 'libmolgrid'
[ 29%] Built target libmolgrid_static
[ 59%] Built target libmolgrid_shared
[ 65%] Built target molgrid
[ 68%] Built target test_grid_cpp
[ 71%] Built target test_transform_cu
[ 75%] Built target test_grid_cu
[ 78%] Built target test_gridinterp_cpp
[ 81%] Built target test_transform_cpp
[ 84%] Built target test_gridmaker_cu
[ 87%] Built target test_mgrid_cpp
[ 90%] Built target test_gridmaker_cpp
[ 93%] Built target test_coordinateset_cpp
[ 96%] Built target test_mgrid_cu
[100%] Built target test_quaternion_cpp
[  0%] Performing install step for 'libmolgrid'
[ 29%] Built target libmolgrid_static
[ 59%] Built target libmolgrid_shared
[ 65%] Built target molgrid
[ 68%] Built target test_grid_cpp
[ 71%] Built target test_transform_cu
[ 75%] Built target test_grid_cu
[ 78%] Built target test_gridinterp_cpp
[ 81%] Built target test_transform_cpp
[ 84%] Built target test_gridmaker_cu
[ 87%] Built target test_mgrid_cpp
[ 90%] Built target test_gridmaker_cpp
[ 93%] Built target test_coordinateset_cpp
[ 96%] Built target test_mgrid_cu
[100%] Built target test_quaternion_cpp
Install the project...
-- Install configuration: "Release"
-- Up-to-date: /home/glinttsd/gnina/build/external/lib/libmolgrid.so
-- Up-to-date: /home/glinttsd/gnina/build/external/lib/libmolgrid.a
-- Up-to-date: /home/glinttsd/gnina/build/external/include/libmolgrid/libmolgrid.h
-- Up-to-date: /home/glinttsd/gnina/build/external/include/libmolgrid/grid.h
-- Up-to-date: /home/glinttsd/gnina/build/external/include/libmolgrid/managed_grid.h
-- Up-to-date: /home/glinttsd/gnina/build/external/include/libmolgrid/quaternion.h
-- Up-to-date: /home/glinttsd/gnina/build/external/include/libmolgrid/transform.h
-- Up-to-date: /home/glinttsd/gnina/build/external/include/libmolgrid/atom_typer.h
-- Up-to-date: /home/glinttsd/gnina/build/external/include/libmolgrid/example.h
-- Up-to-date: /home/glinttsd/gnina/build/external/include/libmolgrid/coordinateset.h
-- Up-to-date: /home/glinttsd/gnina/build/external/include/libmolgrid/exampleref_providers.h
-- Up-to-date: /home/glinttsd/gnina/build/external/include/libmolgrid/example_extractor.h
-- Up-to-date: /home/glinttsd/gnina/build/external/include/libmolgrid/example_provider.h
-- Up-to-date: /home/glinttsd/gnina/build/external/include/libmolgrid/example_dataset.h
-- Up-to-date: /home/glinttsd/gnina/build/external/include/libmolgrid/grid_maker.h
-- Up-to-date: /home/glinttsd/gnina/build/external/include/libmolgrid/grid_interpolater.h
-- Up-to-date: /home/glinttsd/gnina/build/external/include/libmolgrid/coord_cache.h
-- Up-to-date: /home/glinttsd/gnina/build/external/include/libmolgrid/common.h
-- Up-to-date: /home/glinttsd/gnina/build/external/include/libmolgrid/grid_io.h
-- Up-to-date: /home/glinttsd/gnina/build/external/include/libmolgrid/cartesian_grid.h
-- Up-to-date: /home/glinttsd/gnina/build/external/include/libmolgrid/config.h
/usr/lib/python3/dist-packages/setuptools/dist.py:461: UserWarning: Normalizing 'v1.0.1.dev53+gb9ae032f' to '1.0.1.dev53+gb9ae032f'
  warnings.warn(tmpl.format(**locals()))
running install
Checking .pth file support in /home/glinttsd/gnina/build/external/lib/python3.9/site-packages/
/usr/bin/python3.9 -E -c pass
TEST FAILED: /home/glinttsd/gnina/build/external/lib/python3.9/site-packages/ does NOT support .pth files
bad install directory or PYTHONPATH

You are attempting to install a package to a directory that is not
on PYTHONPATH and which Python does not read ".pth" files from.  The
installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:
    /home/glinttsd/gnina/build/external/lib/python3.9/site-packages/
and your PYTHONPATH environment variable currently contains:

Here are some of your options for correcting the problem:

* You can choose a different installation directory, i.e., one that is
  on PYTHONPATH or supports .pth files

* You can add the installation directory to the PYTHONPATH environment
  variable.  (It must then also be on PYTHONPATH whenever you run
  Python and want to use the package(s) you are installing.)

* You can set up the installation directory to support ".pth" files by
  using one of the approaches described here:
  https://setuptools.readthedocs.io/en/latest/easy_install.html#custom-installation-locations
Please make the appropriate changes for your system and try again.
running bdist_egg
running egg_info
writing /home/glinttsd/gnina/build/libmolgrid-prefix/src/libmolgrid-build/python/molgrid.egg-info/PKG-INFO
writing dependency_links to /home/glinttsd/gnina/build/libmolgrid-prefix/src/libmolgrid-build/python/molgrid.egg-info/dependency_links.txt
writing requirements to /home/glinttsd/gnina/build/libmolgrid-prefix/src/libmolgrid-build/python/molgrid.egg-info/requires.txt
writing top-level names to /home/glinttsd/gnina/build/libmolgrid-prefix/src/libmolgrid-build/python/molgrid.egg-info/top_level.txt
reading manifest file '/home/glinttsd/gnina/build/libmolgrid-prefix/src/libmolgrid-build/python/molgrid.egg-info/SOURCES.txt'
writing manifest file '/home/glinttsd/gnina/build/libmolgrid-prefix/src/libmolgrid-build/python/molgrid.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/molgrid
copying build/lib/molgrid/__init__.py -> build/bdist.linux-x86_64/egg/molgrid
copying build/lib/molgrid/molgrid.so -> build/bdist.linux-x86_64/egg/molgrid
copying build/lib/molgrid/torch_bindings.py -> build/bdist.linux-x86_64/egg/molgrid
byte-compiling build/bdist.linux-x86_64/egg/molgrid/__init__.py to __init__.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/molgrid/torch_bindings.py to torch_bindings.cpython-39.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying /home/glinttsd/gnina/build/libmolgrid-prefix/src/libmolgrid-build/python/molgrid.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying /home/glinttsd/gnina/build/libmolgrid-prefix/src/libmolgrid-build/python/molgrid.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying /home/glinttsd/gnina/build/libmolgrid-prefix/src/libmolgrid-build/python/molgrid.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying /home/glinttsd/gnina/build/libmolgrid-prefix/src/libmolgrid-build/python/molgrid.egg-info/not-zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
copying /home/glinttsd/gnina/build/libmolgrid-prefix/src/libmolgrid-build/python/molgrid.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying /home/glinttsd/gnina/build/libmolgrid-prefix/src/libmolgrid-build/python/molgrid.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
creating 'dist/molgrid-1.0.1.dev53+gb9ae032f-py3.9.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing molgrid-1.0.1.dev53+gb9ae032f-py3.9.egg
removing '/home/glinttsd/gnina/build/external/lib/python3.9/site-packages/molgrid-1.0.1.dev53+gb9ae032f-py3.9.egg' (and everything under it)
creating /home/glinttsd/gnina/build/external/lib/python3.9/site-packages/molgrid-1.0.1.dev53+gb9ae032f-py3.9.egg
Extracting molgrid-1.0.1.dev53+gb9ae032f-py3.9.egg to /home/glinttsd/gnina/build/external/lib/python3.9/site-packages

Installed /home/glinttsd/gnina/build/external/lib/python3.9/site-packages/molgrid-1.0.1.dev53+gb9ae032f-py3.9.egg
Processing dependencies for molgrid==1.0.1.dev53+gb9ae032f
Searching for pytest==6.0.2
Best match: pytest 6.0.2
Installing py.test script to /home/glinttsd/gnina/build/external/bin
Installing pytest script to /home/glinttsd/gnina/build/external/bin

Using /usr/lib/python3/dist-packages
Searching for pyquaternion==0.9.9
Best match: pyquaternion 0.9.9
Processing pyquaternion-0.9.9-py3.9.egg

Using /home/glinttsd/gnina/build/external/lib/python3.9/site-packages/pyquaternion-0.9.9-py3.9.egg
Searching for numpy==1.19.5
Best match: numpy 1.19.5
Installing f2py script to /home/glinttsd/gnina/build/external/bin
Installing f2py3 script to /home/glinttsd/gnina/build/external/bin
Installing f2py3.9 script to /home/glinttsd/gnina/build/external/bin

Using /usr/lib/python3/dist-packages
Finished processing dependencies for molgrid==1.0.1.dev53+gb9ae032f
[  0%] Completed 'libmolgrid'
[  1%] Built target libmolgrid
[  1%] Built target caffeproto
[  1%] Linking CUDA device code CMakeFiles/caffe.dir/cmake_device_link.o
nvlink fatal   : Could not open input file '/usr/lib/x86_64-linux-gnu/libpthread.a' (target: sm_86)
make[2]: *** [caffe/src/caffe/CMakeFiles/caffe.dir/build.make:2787: caffe/src/caffe/CMakeFiles/caffe.dir/cmake_device_link.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1387: caffe/src/caffe/CMakeFiles/caffe.dir/all] Error 2
make: *** [Makefile:160: all] Error 2

`
It seems like I have a python related problem (indicated in the middle of output info) and a nvlink problem (indicated in the last of output info)
I also noticed the same problem in #140 
### Your system configuration
Operating system: Ubuntu 21.10
Compiler: gcc 11.2.0
CUDA version (if applicable):11.6
CUDNN version (if applicable): not installed
Python version:3.9.7

**Comment by dkoes** [comment] 2022-03-15 12:01
Duplicate of #140

**Closed by dkoes** 2022-03-15 12:01 UTC
